name: Build and push nightly
on:
  push:
    paths:
      - .github/workflows/build-and-push-nightly.yaml
  pull_request:
    paths:
      - .github/workflows/build-and-push-nightly.yaml
  workflow_dispatch:
    inputs:
      push:
        type: boolean
        default: false
        description: Should the image be pushed

env:
  IMAGE_PROJECT: ${{ vars.IMAGE_PROJECT || 'vshn' }}
  PUSH: ${{ inputs.push || startsWith(github.ref, 'refs/heads/main') }}

jobs:
  build-and-push-nightly:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          # renovate: datasource=github-tags packageName=chainguard-dev/kaniko
          ref: v1.25.3
          repository: chainguard-dev/kaniko.git

      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef #v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        id: build
        with:
          context: .
          file: ./deploy/Dockerfile
          push: ${{ env.PUSH }}
          tags: ghcr.io/${{ env.IMAGE_PROJECT }}/kaniko:nightly-debug
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: kaniko-debug
